### PR TITLE
fix(wallet): basic coin selection on spend

### PR DESCRIPTION
**Pull request by humanumbrella**
## Description

Allow UTXO selection on spend. Works in both Redeem Script and Wallet interfaces but the Wallet interface is not 100% feature complete. E.g. if you try to spend a single utxo from multiple addresses that will not work properly right now. However, within a multi-address setup, you should be able to do coin selection.

## Does this PR introduce a breaking change?

* [ ] Yes
* [x] No

## Does this PR fix an open issue?

* [x] Yes
* [ ] No

Partially addresses https://github.com/unchained-capital/caravan/issues/54

### CODE REVIEW

**Comment by waldenraines** [comment]
Any way to disable the automatic scrolling (I think due to the error)?  It's pretty annoying when attempting to select/deselect multiple UTXOs:

Peek 2021-06-01 11-39

**Comment by waldenraines** [comment]
@humanumbrella do we want to disable the UTXO selection after the transaction has been authored (similar to how we disable everything else):

Peek 2021-06-01 14-53

**Comment by humanumbrella** [comment]
Yes, that makes sense. Looking.

**Review by dhruvbansal — APPROVED** [review]
LGTM

**Review by waldenraines — APPROVED** [review]

**Pull request merged**
