### PR TITLE
Upgrade NodeJS to support >= v16

### PR DESCRIPTION
**Pull request by Shadouts**
Older versions of `node-sass` are incompatible with newer versions of NodeJS and newer `node-sass` is conflicting with other required versions of `node-sass`. `sass` is a recommended replacement for `node-sass` to address these issues. See: 
https://www.npmjs.com/package/node-sass
https://stackoverflow.com/questions/64625050/error-node-sass-version-5-0-0-is-incompatible-with-4-0-0

## Description

Between NodeJS v14 and 15, many packages received maintenance updates, however, `node-sass` v4 became incompatible. It is recommended to instead use the `sass` package as a replacement.

### Steps taken to perform the package upgrade
1. Using NodeJS v14: `npm remove node-sass`
2. Using NodeJS v16: `npm i sass`

## Does this PR introduce a breaking change?
* [ ] Yes
* [x] No
It shouldn't.

## Does this PR fix an open issue?

* [x] Yes
* [ ] No
Partially fixes https://github.com/unchained-capital/caravan/issues/225 This issue might still be present when node version is greater than 16.

### CODE REVIEW

**Comment by bucko13** [comment]
Hell yeah. Good catch. Any chance you could put this on a branch of your repo that's not `master` so it's easier to test/verify locally. There might be some git-fu I'm unaware of to get around it but I don't know how to checkout the master branch of another remote.

**Comment by robertshuford** [comment]
@bucko13 If your fork is setup like mine, this is what I did to check it out locally:
```sh
git fetch upstream pull/279/head:pr-279
git checkout pr-279
```

**Review by humanumbrella — APPROVED** [review]
awesome, ty! appears to work on my end.

**Review by waldenraines — APPROVED** [review]
```
> node -v; npm i
v16.14.0

added 2876 packages in 15s
```

**Pull request merged**
