### PR TITLE
Fix some styling issues

### PR DESCRIPTION
**Pull request by waldenraines**
## PR Type

* [x] Bug fix
* [ ] Feature
* [ ] Code style update (whitespace, formatting, missing semicolons, etc.)
* [ ] Refactor (i.e., no functional changes)
* [ ] Build related changes
* [ ] CI related changes
* [ ] Documentation changes
* [ ] Other (please describe below):

## Description
- Remove the return button on the receive page
- Left justify send/preview transaction buttons to match elsewhere
- Move edit transaction button to bottom
- Fix error message when output is greater than balance
- Move wallet tabs into cards to make them consistent
- Fix alignment of footer

## Does this PR introduce a breaking change?

* [ ] Yes
* [x] No

## Does this PR fixes open issues?

* [ ] Yes
* [x] No

### CODE REVIEW

**Comment by waldenraines** [comment]
Peek 2020-04-24 13-24

**Comment by waldenraines** [comment]
Peek 2020-04-24 16-05

**Comment by bucko13** [comment]
Conflict introduced with the other PR you just put in, but otherwise LGTM. Thanks!

**Comment by waldenraines** [comment]
> Conflict introduced with the other PR you just put in, but otherwise LGTM. Thanks!

Resolved, thanks for the review!

**Pull request merged**
